AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: MARKET Lambda functions.

Resources:
  getwhitelist:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: whitelist/list.getwhitelist
      Runtime: nodejs8.10
      CodeUri: .
      Description: Get whilelisted contract addresses.
      MemorySize: 1024
      Timeout: 6
      Environment:
        Variables:
          CONTRACT_ADDRESS: '0x06e28E90107e015f12DAE4F2FF0C6750eF225620'
          GAS_LIMIT: '100000'
          GAS_PRICE: '20000000000'
          OWNER_ADDRESS: '0x8a6C7Ea2C27827093825e5FdD57BD564312c6a2c'
          OWNER_PRIVKEY: '<PRIVATE KEY HERE>'
          PROVIDER_URL: 'https://rinkeby.infura.io/cbHh1p8RT4Q6E97F4gVi'

  create:
    Type: AWS::Serverless::Function
    Properties:
      Handler: whitelist/create.create
      Runtime: nodejs8.10
      CodeUri: .
      Description: Create a whilelisted contract.
      MemorySize: 1024
      Timeout: 6
      Environment:
        Variables:
          CONTRACT_ADDRESS: '0x06e28E90107e015f12DAE4F2FF0C6750eF225620'
          GAS_LIMIT: '100000'
          GAS_PRICE: '20000000000'
          OWNER_ADDRESS: '0x8a6C7Ea2C27827093825e5FdD57BD564312c6a2c'
          OWNER_PRIVKEY: '<PRIVATE KEY HERE>'
          PROVIDER_URL: 'https://rinkeby.infura.io/cbHh1p8RT4Q6E97F4gVi'